### ISSUE TITLE
Implement Child Register page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#17]
<img width="337" alt="screen shot 2018-12-06 at 12 08 28 pm" src="https://user-images.githubusercontent.com/3488986/49573820-fef4f880-f94f-11e8-882d-a6ad6a36a870.png">

- [x] Top left menu button opens side menu (#7)
- [x] Swiping from the left also opens side menu
- [x] Dynamic search bar (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/12)
- [x] Please change the text in the dynamic search to read "Search name or ID"
- [x] Due only toggle (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/41)
- [x] First line shows "CG: {first_name} {middle_name} {surname}" where CG stands for caregiver, so you show the name of the primary caregiver in the family.
- [x] Second line shows the child's {first_name} {middle_name} {surname}, followed by their age (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/18)
- [x] Third line shows the family's address, {village_town} from Family Registration form then the child's gender {sex}
- [x] Status of the child's home visit shown on the right (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/13)
- [x] Home button at the bottom takes the user back to the main register page for whichever register they're currently in.
- [x] Scan QR needs to be configurable - it should be an option, but for this first release for Liberia, they are not using QR codes, so it should not be shown in the bottom navigation menu. Other countries in West Africa may use it though, so it should be configurable.
- [x] Add family opens the add family registration form
- [x] Job Aids is a placeholder for now. It will eventually house short training videos and the user guide in pdf format.

**Comment by mahmud6390** [comment]
![screenshot_2019-01-08-19-55-36-897_org smartgresiter wcaro](https://user-images.githubusercontent.com/2793306/50835936-2b05fe00-1382-11e9-982a-f1ae931106f0.png)
>>right now status showing based on home visit screen submit button press.
fully function able when home visit screen all function done.

**Comment by cagulas** [comment]
QA 21 Jan:

- [ ] Caregiver and child's name and age should be medium font, not bold
- [ ] A period is being used between address and gender instead of an interpunct. Please replace.
- [ ] The line that separates the demographic info (first column) from the second column with the visit status is missing. 
- [ ] Related to the above point, only the red and blue are actual buttons. Visit done and visit not done are not buttons, they're just labels in the column. See the mockup above.
- [ ] Can we reduce the height of the home visit button? See mockups. The button shouldn't take up the full height of the row. Also, I think the row itself is too tall. We can reduce the height of each row I think. The button should be widened a bit as well. "Visit not" and "Home Visit" should fit on one line in the button labels. Pls refer to mockups.
- [ ] Inconsistent wording on the home visit button - Child Subha Mah row says "Record Visit" while the next row says "Record Home Visit". It should be the latter.
- [ ] {middle_name} of the CG is not included right now. Please add.
- [ ] {middle_name} of the child is not included right now. Please add.
- [ ] When you tap on Add Family and then go back to the child register list, the Home icon on the bottom should be in blue font again. Right now, it remains on Add Family. This should work whereby anytime you land on the home register page, it should go back to the Home icon being selected.

**Comment by mahmud6390** [comment]
Add these changes in pending PR
https://github.com/OpenSRP/opensrp-unicef-wcaro/pull/106

**Comment by mahmud6390** [comment]
Added last option in this pending PR(#106).

**Comment by cagulas** [comment]
Lgtm. A couple more issues have been created in a new issue: https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/122
