### ISSUE TITLE
Implement floating action button on Family Profile page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#22]
<img width="415" alt="screen shot 2018-12-03 at 8 36 47 pm" src="https://user-images.githubusercontent.com/3488986/49390924-4b1b1f80-f73b-11e8-8ece-5f18e7ab7868.png">

- [x] Call (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/25)
- [x] Family details (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/26)
- [x] Add family member (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/27)
- [x] Remove existing family member (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/28)
- [x] Change family head (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/30)
- [x] Change primary caregiver (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/31)

**Comment by faith-mutua** [comment]
QA 29 Jan:

Looks good to me
