### ISSUE TITLE
Implement Child profile page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#43]
<img width="341" alt="screen shot 2018-12-07 at 11 24 34 am" src="https://user-images.githubusercontent.com/3488986/49636115-b4888000-fa12-11e8-8c64-38da279a995b.png">

- [x] The child profile page is what you land on when you click on the a child in the register list (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/17) or if you click on a child's row within the family profile member page (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/21)
- [x] Back arrow takes the user back to the child register list. Use "Return to all children" as the label.
- [x] The top background is very light blue for boys. For girls, use light pink as the background.
- [x] Child's image from registration form (`image`) or child avatar if no image taken.
- [x] "CG: `first name` `middle name` `last name`" where CG stands for caregiver. Use the name of the person in the family who is assigned the primary caregiver role.
- [x] "`first name` `middle name` `last name`" of the child from the U5 child registration form. Followed by age (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/18)
- [x] Next row shows gender (`sex`), then `village_town` of the child's family from the Family Registration form, then the child's ID number from their registration form (`opensrp_id`). Use a middle dot (interpunct) to separate these.
- [x] Visit buttons (separate issue to be created to explain these)
- [x] Last visit 40 days ago row shows the date of the last child home visit. If there is no previous home visit (i.e. the child was just registered), then don't show this row yet. 
- [x] Tapping on this row opens the Medical History page for the child (separate issue to be created)
- [x] The next row shows either the most overdue/due service for the child, OR, if there are currently no overdue/due services, then it shows the next upcoming service that is due.
- [x] If the service is overdue, use red font (as shown in above mockup) and show the original due date for that service. 
- [x] If the service is due, use normal black font and still show the due date.
- [x] If no services are due or overdue, just show the next upcoming service in grey front (same as the "View upcoming services" text, and the upcoming due date (in the future).
- [x] Tapping on this row opens the upcoming services page (separate issue to be created)
- [x] The final row links back to the family profile due tab (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/23)
- [x] If the family has nothing due, show what's in the mockup above. Note: if only the child whose profile you are currently on has due services but no one else in the family does, use the "Family has nothing due" status.
- [x] If someone else in the family has services that are overdue, use the below text and red font:

<img width="288" alt="screen shot 2018-12-07 at 11 39 47 am" src="https://user-images.githubusercontent.com/3488986/49636856-ddaa1000-fa14-11e8-98a1-6c08895179a1.png">

- [x] If someone else in the family has services that are due, use "Family has services due" text in normal black font.

**Comment by mahmud6390** [comment]
visit status,service status,family member service status updated from data.

**Comment by mahmud6390** [comment]
>>working on view upcoming service screen.right now only show the status.
![screenshot_2019-01-08-19-54-31-410_org smartgresiter wcaro](https://user-images.githubusercontent.com/2793306/50835594-52a89680-1381-11e9-8b68-9b41970ef1f2.png)

**Comment by cagulas** [comment]
@mahmud6390:

<img width="583" alt="screen shot 2019-01-10 at 12 54 55 pm" src="https://user-images.githubusercontent.com/3488986/50960781-374f9f80-14d7-11e9-8480-f280e115de70.png">

Some feedback so far (refer to side by side of what’s implemented vs. original mockup, above):

- [ ] The font size, color, bolding, etc. needs to be improved throughout the page to better match the mockup. The demographic details at the top don’t need to be bolded, for example. The last visit, BCG, and family services rows can be darker font and one size larger I think. The EDIT button should also be slightly more prominent.
- [ ] Add a space after CG: and before family name and add a space after comma and before child’s age.
- [ ] The interpunct (https://en.wikipedia.org/wiki/Interpunct) is not correct.
- [ ] The blue background at the top is meant to be more subtle, enough where the “Return to all children” should be in blue font, as seen in the mockups. Add more space between this and the top of the child’s image or avatar.
- [ ] Alternative to the above, we can make the top a light grey background and add a light blue outline around the child’s picture/avatar (see below). 

<img width="293" alt="screen shot 2019-01-10 at 12 56 42 pm" src="https://user-images.githubusercontent.com/3488986/50960895-7aaa0e00-14d7-11e9-8129-1911004905f2.png">

- [ ] Please use the correct asset from https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/10 for the child avatar. Look in family profile section.
- [ ] Spacing issues in BCG overdue (remove extra space after BCG and add space between overdue and due date.
- [ ] Add “than” so it’s “Last visit less than 24 hrs ago” 
- [ ] In Android, I think we can make the top phone status bar (where it shows network, battery level, etc.) take on the background color of the app on every screen. Right now, it looks like it turns purple. Is this possible?

**Comment by cagulas** [comment]
<img width="404" alt="screen shot 2019-01-10 at 1 05 15 pm" src="https://user-images.githubusercontent.com/3488986/50961306-66b2dc00-14d8-11e9-9c3c-6f03ba275d11.png">

For the visit buttons, see comparison above. The buttons need to be spaced equally in the row, so equal spacing in the margins and between the two buttons. The text in the button needs to be more prominent; right now it’s really hard to read.

**Comment by cagulas** [comment]
@mahmud6390 For the child avatar circle colors: they are 3px, Blue is #C7E7FE and Pink is #FFDAF7

**Comment by cagulas** [comment]
QA 21 Jan:

Looking much better!

- [ ] Let's reduce the space between the back arrow and the "Return to all children" label. See the family profile page for a good example.
- [ ] We're missing a line between the visit buttons and the upcoming services row. See the mockup above. I think we also need to widen the row for the visit buttons, so add some room between the top header containing demographic details and the visit button row.

**Comment by mahmud6390** [comment]
Middle name added in this pending PR
https://github.com/OpenSRP/opensrp-unicef-wcaro/pull/106

**Comment by cagulas** [comment]
@mahmud6390 

- [ ] Can we add some space between the "return to all children" and the top of the child's avatar? They look just slightly too close together.
- [ ] Can we also add the same line that separates upcoming services to family has services due to the border between the top demographic section and the visit button row?

**Comment by mahmud6390** [comment]
added with same pending PR

**Comment by cagulas** [comment]
@mahmud6390 I just realized that the family has services overdue is not correct. I registered a new family and family head and then I registered one child. On the child's profile page, it says family has services overdue, but this is not correct. We are viewing the child's profile page, so the family has services due should only show if someone else in the family has services due, i.e. another child.

**Comment by mahmud6390** [comment]
fixed this in pending PR #106

**Comment by raihan-mpower** [comment]
@cagulas will this show due only in case of another child of same family has pending home visit?

**Comment by cagulas** [comment]
@raihan-mpower Yep, exactly. Is this how @mahmud6390 fixed this in PR 106? Or is this something you still need to change?

**Comment by mahmud6390** [comment]
Yeah i need to handle "visit not done" stage also for another child in that family.Fixing will be add this pending PR.

**Comment by mahmud6390** [comment]
fixed added in this pending PR #106

**Comment by cagulas** [comment]
Lgtm
