### ISSUE TITLE
Implement Families Register page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-unicef-wcaro#8]
Marvel prototype: https://marvelapp.com/9j1277a/screen/48411528

<img width="353" alt="screen shot 2018-12-06 at 12 07 48 pm" src="https://user-images.githubusercontent.com/3488986/49575102-f651f180-f952-11e8-9f50-e257e2c7a7f3.png">

- [x] Top left menu button opens side menu (#7)
- [x] Swiping from the left also opens side menu (#7)
- [x] Dynamic search bar (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/11)
- [x] Please change the text in the dynamic search to read "Search name or ID"
- [x] Due only toggle (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/41)
- [x] Row shows "{fam_name} Family" from Family Registration form
- [x] Icons show each female, male child in the family. Get the icons from Roger when you start on this issue. We're not doing pregnant women yet.
- [x] Where you see "Lavington #445", use the {village_town} from the Family Registration form
- [x] Status of the family's home visit shown on the right. I am creating a separate issue for these (https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/14)
- [x] Home button at the bottom takes the user back to the main register page for whichever register they're currently in.
- [x] Scan QR needs to be configurable - it should be an option, but for this first release for Liberia, they are not using QR codes, so it should not be shown in the bottom navigation menu. Other countries in West Africa may use it though, so it should be configurable.
- [x] Add family opens the add family registration form (issue to be created)
- [x] Job Aids is a placeholder for now. It will eventually house short training videos and the user guide in pdf format.

**Comment by cagulas** [comment]
Replaced the image above with a slightly updated mockup.

**Comment by keymane** [comment]
@cagulas @rowo how does the sort menu look like.  I can't seem to find the mockup for that page

**Comment by cagulas** [comment]
@keymane still in progress. I'll create the issue when it's finalized. This issue is blocking it it seems: https://github.com/OpenSRP/opensrp-unicef-wcaro/issues/4

**Comment by cagulas** [comment]
@keymane The sort/filter discussion was finalized (at least from the UI side), so I've replaced the mockup above. This should be final now.

**Comment by cagulas** [comment]
QA 4 January:

- [ ] The phone status bar for some reason doesn't take on the background color from the app. Instead, it turns a dark purple color. See below.
- [ ] All Families header is not centered
- [ ] Reduce the space between "All Families" and search bar
- [ ] Remove the 0 clients row. We're not including here, because we have total number of clients in the side menu now.

**Comment by rkodev** [comment]
Sorf filter replaced by the due filter

**Comment by faith-mutua** [comment]
QA 04 Feb

Lgtm

**Comment by cagulas** [comment]
QA 6th Feb release:

- [ ] After you add a family, the bottom menu should switch back and highlight the Home menu option again; right now, it stays highlighted on Add family.
- [ ] I think something broke in this release and the address field is not appearing below the Family name. I was logged in as chaone and I added the Smith Family and when it was registered, the register only showed Smith Family and not the address. Other addresses are also not showing for me for other families that sync.
- [ ] The line that separates the demographic info from the visit button is a darker font than the line that separates the rows. These should be the same light grey font. See mockup above.
- [ ] The Family name should be medium font, not bold. Also made this comment for the Child Register page.
- [ ] I think we can increase the width of the home visit button. "Home Visit" in Record Home visit should fit on one line. If that happens, we can decrease the height of the button and the entire row for each family record.

**Comment by rkodev** [comment]
All issues have been resolved

**Comment by cagulas** [comment]
Lgtm
